### ISSUE TITLE
Feature Request: Copy without ' char

### ISSUE THREAD

**Issue by ldsands** [malashevskyi/vs-code-copy-workspace-path#1]
Thanks for the handy extension, I use it quite a bit! Would you be willing to try and add an option to copy the path without the single quote (') symbol?

I might take a stab at it but it wouldn't be for quite a while, and I'm mostly self-taught in python. My brief adventure with TS in the past was very time-consuming. So I thought I would ask you first. Hope you don't mind the question.

**Comment by tonisives** [comment]
It is obviously an easy fix, just remove the extra ' in here:

https://github.com/malashevskyi/vs-code-copy-workspace-path/blob/master/src/extension.ts#L17

I think it would make sense to not have the extra '' appended as default


PS: Thanks for this nice little extension👍🏽

**Comment by malashevskyi** [comment]
@ldsands Sorry, somehow I missed this issue and only now saw it due to @tonisives comment. Thanks.

I added an option to the configuration (add single quotes to your path). That is checked by default.

PS: I am surprised that it is useful for someone 😀
